
version: '3'
services:


  mssql:
    networks:
      - waybot_network
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Strong(!)Password
    volumes:
      - mssqlfixtures:/docker-entrypoint-initdb.d
    ports:
      - "1433:1433"

networks:
   waybot_network:

volumes:
  mssqlfixtures:

