
version: '3'
services:

  mssql:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Strong(!)Password
    volumes:
      - fixtures:/fixtures
    ports:
      - "1433:1433"

volumes:
  fixtures:
